name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Integration Test
      run: |
        ./hack/initializeTestCluster.sh
        go test -v -coverpkg=./... -coverprofile=profile.cov ./...
        go tool cover -func profile.cov
